### PR TITLE
Fix Issue Mentioned

### PR DESCRIPTION
**Pull request by yas19sin**
Changed code where it used to look for 'link' in the results_list where now it is 'url_suffix' which returns the correct video watch address.

### CODE REVIEW

**Comment by devivoc** [comment]
bump^

**Comment by yas19sin** [comment]
@devivoc you are better off writing a new program instead of fixing an existing one, it'll take less time, trouble, disappointment.

**Comment by Aku-Origin** [comment]
Hello i've got some issues, it's close itself pretty quickly after this line: 
Spotypynotworking get this

**Comment by JayChen35** [comment]
> 
> 
> @devivoc you are better off writing a new program instead of fixing an existing one, it'll take less time, trouble, disappointment.

Hey @yas19sin and @devivoc; apologies for not jumping on this issue quicker. To be completely honest and upfront, I made this tool more for myself instead of something super reliable that is regularly maintained. I'm glad you found what I made useful anyway, and were able to fix issues I didn't foresee. Apologies for any inconveniences. I'll approve this PR for future users. Thanks!

**Pull request merged**
